kind: Blueprint
apiVersion: cr.kanister.io/v1alpha1
metadata:
  name: postgresql-hooks
  namespace: kasten-io
actions:
  backupPrehook:
    name: ""
    kind: ""
    phases:
      - func: KubeExec
        name: makePGCheckPoint
        args:
          command:
            - bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - >
              PGPASSWORD=${POSTGRES_POSTGRES_PASSWORD} psql -d
              ${POSTGRES_DATABASE} -U postgres -c "CHECKPOINT;"
          container: postgresql
          namespace: "{{ .StatefulSet.Namespace }}"
          pod: "{{ index .StatefulSet.Pods 0 }}"
