INSERT INTO stock(product,unit,amount,price) VALUES ('Veeam VBR','Socket',0.0,2000);
INSERT INTO stock(product,unit,amount,price) VALUES ('Veeam VBR','VUL (10 pack)',10000.0,1500);
INSERT INTO stock(product,unit,amount,price) VALUES ('Kasten K10','Node',10000.0,1500);
INSERT INTO stock(product,unit,amount,price) VALUES ('Veeam Backup for M365','User',10000.0,1500.0);
INSERT INTO stock(product,unit,amount,price) VALUES ('Veeam Backup for Salesforce','User',0.0,10000.0);
